import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";

interface IHomeProps {
  users: {
    id: string;
    name: string;
    email: string;
    surname: string;
  }[];
}

const AddNewItem: NextPage = () => {
  const router = useRouter();

  const [name, setName] = useState("");
  const [surname, setSurname] = useState("");
  const [email, setEmail] = useState("");

  const addUser = async () => {
    const res = await fetch(
      `http://localhost:${process.env.NEXT_PUBLIC_PORT}/add-item`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name,
          surname,
          email,
        }),
      }
    );
    const data = await res.json();
    router.push("/");
  };

  return (
    <>
      <Head>
        <title>Users 1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Add user
          </h1>

          <form
            onSubmit={(e) => {
              e.preventDefault();
              e.stopPropagation();
              addUser();
            }}
            className="w-full space-y-2 rounded-xl bg-white/10 bg-white/10 p-4 text-white"
          >
            <div>
              <label>Name</label>
              <input
                value={name}
                required
                onChange={({ target: { value } }) => setName(value)}
                className="input w-full px-4 py-2 text-black "
                type="text"
              />
            </div>
            <div>
              <label>Surname</label>
              <input
                value={surname}
                required
                onChange={({ target: { value } }) => setSurname(value)}
                className="input w-full px-4 py-2 text-black"
                type="text"
              />
            </div>
            <div>
              <label>Email</label>
              <input
                value={email}
                required
                onChange={({ target: { value } }) => setEmail(value)}
                className="input w-full px-4 py-2 text-black"
                type="email"
              />
            </div>

            <button className="w-full rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700">
              Add
            </button>
          </form>
        </div>
      </main>
    </>
  );
};

export default AddNewItem;
