import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";

interface IHomeProps {
  users: {
    id: string;
    name: string;
    email: string;
    surname: string;
  }[];
}

export const getServerSideProps = async () => {
  const res = await fetch(
    `http://localhost:${process.env.NEXT_PUBLIC_PORT}/get-users`
  );
  const data = await res.json();

  return {
    props: { users: data },
  };
};

const Home: NextPage<IHomeProps> = ({ users: usersProp }) => {
  console.log(process.env.NEXT_PUBLIC_PORTT);
  const router = useRouter();
  const [users, setUsers] = useState(usersProp || []);
  console.log(users);

  const removeUser = async (id: string) => {
    const res = await fetch(
      `http://localhost:${process.env.NEXT_PUBLIC_PORT}/remove-user?id=${id}`
    );

    const data = await res.json();

    if (data.success) {
      setUsers(users.filter((user) => user.id !== id));
    }
  };

  return (
    <>
      <Head>
        <title>Users 1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            User table
          </h1>

          <table className="w-full table-auto rounded-xl bg-white/10 bg-white/10 text-white">
            <thead>
              <tr>
                <th className=" p-3 text-left ">Name</th>
                <th className="p-3 text-left">Surname</th>
                <th className="p-3 text-left">Email</th>
                <th className="p-3">Action</th>
              </tr>
            </thead>
            <tbody>
              {users.map(({ id, name, surname, email }) => (
                <tr key={id}>
                  <td className="px-3 py-2">{name}</td>
                  <td className="px-3 py-2">{surname}</td>
                  <td className="px-3 py-2">{email}</td>
                  <td className="px-3 py-2 text-center">
                    <button
                      className="mr-2 underline hover:no-underline"
                      onClick={() => removeUser(id)}
                    >
                      del
                    </button>
                    <button
                      className="underline hover:no-underline"
                      onClick={() => router.push("edit/" + id)}
                    >
                      edit
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default Home;
