version: "3"
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: projekt
    volumes:
      - db:/var/lib/mysql
  api:
    image: node:lts-alpine
    build: api/.
    depends_on:
      - db
    ports:
      - "3001:3001"
    env_file: api/.env
    environment:
      - DB_NAME=projekt
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_PORT=3306
      - NODE_DOCKER_PORT=3001
      - NODE_ENV=production 
    volumes:
      - ./api/:/home/app/
      - /api/home/app/node_modules
volumes: 
  db: